### PR TITLE
Fix: overflow and adjust background image colors

### LINKED ISSUE #39: Login screen small device overflow and ui enhancements
## Generic information
- OS name and version: iOS 13.5.1
- Application build code: 4015
- Network type (mobile/Wi-Fi):  mobile and Wi-Fi

## Bug description

Login screen on smaller devices are overflowing at the bottom.

Enhancements:

- Turn login options in to columns
- Change background color for both light and dark mode to match wireframe

## Steps to reproduce
 
1. Open the app
image

## Expected behavior

The T&C should be responsive at the bottom.

- Background color should follow more closely with wireframe
image

### PR DESCRIPTION
**Pull request by ryuash**
## Description

Closes #39 
## Checklist
- [x] Targeted PR against correct branch.
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [x] Wrote unit tests. 
- [x] Updated the documentation. 
- [x] Added an entry to the `CHANGELOG.md` file.
- [x] Re-reviewed `Files changed` in the Github PR explorer.

### CODE REVIEW

File: lib/ui/theme/decorations.dart [hunk 1]
```diff
@@ -3,30 +3,41 @@ import 'package:mooncake/ui/theme/colors.dart';
...
+          'alignment': Alignment(0.5, 0.5),
+        };
       default:
-        return [Color(0xFF1B1659), Color(0xFF11101D)];
+        return {
+          'colors': [Color(0xFF020207), Color(0xFF0D0B21)],
+          'pattern': AssetImage("assets/images/pattern_dark.png"),
+          'opacity': 0.35,
+          'alignment': Alignment.bottomCenter,
+        };
```
Comment (rmontagnin) [inline lib/ui/theme/decorations.dart:21]: Holy smokes this looks super clean :100:

File: lib/ui/widgets/login/login_terms_conditions.dart [hunk 2]
```diff
@@ -5,6 +5,10 @@ import 'package:url_launcher/url_launcher.dart';
 
 /// Allows to view Mooncake terms and conditions
 class LoginTermsAndConditions extends StatelessWidget {
+  final String align;
```
Comment (rmontagnin) [inline lib/ui/widgets/login/login_terms_conditions.dart]: What about using a `TextAlign` property directly and setting it as `TextAlight.start` by default instead of a String here?
Do you think that's possible?

**Review by rmontagnin — CHANGES_REQUESTED** [review]
Just one thing to change IMO, otherwise ready to be merged. 

We need to figure out formatting tho, I would hate to have thousands of files changed every time :joy:
