### PR TITLE
UI and UX improvements

### LINKED ISSUE #57: Post time not reported properly
## Generic information
- OS name and version: Both
- Application build code: N.A.
- Network type (mobile/Wi-Fi): Both

## Bug description
Inside a single post item, the posting time does not appear correct. After a minute that a post has been created, the text displays "A couple of hours ago". This is due to the fact that the time is considered to be in UTC instead of the local user time zone. 

## Steps to reproduce
1. Create a post
2. Wait a few minutes
3. Look at the posting time

## Expected behavior
The posting time should be appropriately displayed based on the current timezone of the user, not UTC.

### LINKED ISSUE #69: Post messages not displaying new lines properly
## Generic information
- OS name and version: Android 10
- Application build code: `4018`
- Network type (mobile/Wi-Fi): Both

## Bug description
Currently the posts are not displaying newline characters (`\n`, `\r`) properly. All messages are shown as one-liners.

## Steps to reproduce
1. Create a post with multiple lines. 
2. Look at the post message.

## Expected behavior
The post message should be viewed as a multi-lines message, instead of a single liner.

### LINKED ISSUE #70: Improve recover account wrong password feedback
## Generic information
- OS name and version: iOS 
- Application build code: `4018`
- Network type (mobile/Wi-Fi): Both

## Bug description
When recovering an account from a mnemonic backup, if the user inputs the wrong password while recovering it the screen does not tell anything to the user itself. 

## Steps to reproduce
1. Export the account as a mnemonic backup
2. Try recovering it with a wrong password.

## Expected behavior
An alert should be seen telling the password or input text is incorrect.

### LINKED ISSUE #71: View mnemonic read check
When the user wants to view the mnemonic, currently it has to go through the following warning screen. The problem is that he can tap on the "View mnemonic" button without reading the warning text.

## Implementation proposal
We should also ask him to check a checkbox to make sure he's read it.

### LINKED ISSUE #74: Allow the edit of a profile biography
## Generic information
- OS name and version: iOS
- Application build code: `4018`
- Network type (mobile/Wi-Fi): Both

## Bug description
Currently the user is not able to edit the biography without re-writing everything.

## Steps to reproduce
1. Try editing your profile, saving a biography.
2. Go back, enter the edit screen again and click on the bio field.

File-from-iOS-1

## Expected behavior
The user should be able to edit the biography properly.

### LINKED ISSUE #76: Font is not rendering correctly on iOS device
The native iOS font `SF Pro` is being displayed improperly. The text looks narrower than normal and the letter spacing is too tight. 

XD on the left vs iOS screen capture on the right
image

This is due to the fact that Flutter is not handling the font on iOS 13+ correctly.

https://github.com/flutter/flutter/issues/43998
https://github.com/flutter/flutter/issues/60013

Interestingly, the font display correctly with Markdown.

IMG_5092

This comment may give some light.
https://github.com/flutter/flutter/issues/41101#issuecomment-577036976

### PR DESCRIPTION
**Pull request by rmontagnin**
## Description
This PR implements various UI and UX fixes. Particularly: 

- Fixed the visualization of posts' times (fixes #57)
- Improved the post message visualization (fixes #69) 
- Improved the wrong recovery password (fixes #70) 
- Added the read check inside the view mnemonic screen (fixes #71)
- Improved the edit of the account (fixes #74)
- Improved the font visualization on iOS devices (fixes #76)

## Checklist
- [x] Targeted PR against correct branch.
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Wrote unit tests.
- [x] Run flutter format.
- [ ] Updated the documentation.
- [x] Added an entry to the `CHANGELOG.md` file.
- [ ] Re-reviewed `Files changed` in the Github PR explorer.

### CODE REVIEW

File: lib/ui/localization/export.dart [hunk 1]
```diff
@@ -104,13 +106,15 @@ see your mnemonic will most surely end in them stealing your account and all
 your funds so proceed with caution.
 """;
   String get securityLoginBiometrics => """
-If you understand the risks of viewing your mnemonic, please tap below to
-start the authentication process.
+If you understand the risks of viewing your mnemonic, please check the below
```
Comment (ryuash) [inline lib/ui/localization/export.dart]: the wording is a little bit weird. Maybe `please select the checkbox below to start the authentication process`

File: lib/ui/localization/export.dart [hunk 2]
```diff
@@ -104,13 +106,15 @@ see your mnemonic will most surely end in them stealing your account and all
...
+checkbox and tap below to start the authentication process.
 """;
   String get securityLoginPassword => """
-If you understand the risks of viewing your mnemonic, please insert below
-your password and press the button to view it
+If you understand the risks of viewing your mnemonic, please check the below
+checkbox, insert your password and press the button to view it.
```
Comment (ryuash) [inline lib/ui/localization/export.dart]: same as above. The `check the below checkbox` doesn't seem natural

File: lib/ui/localization/export.dart [hunk 3]
```diff
@@ -104,13 +106,15 @@ see your mnemonic will most surely end in them stealing your account and all
...
 """;
+  String get understoodMnemonicDisclaimer =>
+      "I've understood the consequences of viewing my mnemonic.";
```
Comment (ryuash) [inline lib/ui/localization/export.dart]: `I understand the consequences of viewing my mnemonic.` <- sounds better unless this is meant to be put in past tense

File: lib/ui/localization/export.dart [hunk 4]
```diff
@@ -106,11 +106,11 @@ see your mnemonic will most surely end in them stealing your account and all
 your funds so proceed with caution.
 """;
   String get securityLoginBiometrics => """
-If you understand the risks of viewing your mnemonic, please check the below
+If you understand the risks of viewing your mnemonic, please select the below
 checkbox and tap below to start the authentication process.
 """;
   String get securityLoginPassword => """
-If you understand the risks of viewing your mnemonic, please check the below
+If you understand the risks of viewing your mnemonic, please select the below
```
Comment (ryuash) [inline lib/ui/localization/export.dart]: please select the **checkbox below** *is more natural* then please select the **below checkbox**

**Review by ryuash — APPROVED** [review]

**Review by ryuash — APPROVED** [review]
