### PR TITLE
fix: sync popup error

### LINKED ISSUE #100: Cannot see message error
## Generic information
- OS name and version: Android/iOS
- Application build code: `4102`
- Network type (mobile/Wi-Fi): Both 

## Bug description
If an error is presented during the sync of the message, it's not possible to view what caused it. 

## Steps to reproduce
Get a message to fail sync. Now you can't see the error. 

## Expected behavior
Few versions ago, there was the possibility of long tapping the message to view the error if the transactions was not successful, or the transaction hash if the sync was successful. I think the expected behavior we would like to have it that one. 

Also, we should implement the logging of transactions errors using `Logger.log` which will send any error to our remote reporting tool so that it can be further investigated.

### PR DESCRIPTION
**Pull request by ryuash**
## Description

fixes #100 
## Checklist
- [x] Targeted PR against correct branch.
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Wrote unit tests.
- [x] Run flutter format.
- [ ] Updated the documentation.
- [x] Added an entry to the `CHANGELOG.md` file.
- [x] Re-reviewed `Files changed` in the Github PR explorer.

### CODE REVIEW

File: lib/repositories/posts/posts_repository_impl.dart [hunk 1]
```diff
@@ -154,6 +155,11 @@ class PostsRepositoryImpl extends PostsRepository {
       await _localSettingsSource.save(
           SettingKeys.TX_AMOUNT, currentTxAmount + updatedPosts.length);
     }
+
+    // logs to sentry
+    if (status.value == PostStatusValue.ERRORED) {
+      Logger.log(status.data);
+    }
```
Comment (rmontagnin) [inline lib/repositories/posts/posts_repository_impl.dart]: I think it's probably better to move this inside the `chainSoure.sendTx` method so that we can log other transactions (like the account-related ones) as well.

**Review by rmontagnin — COMMENTED** [review]
Great catch! I would change only one thing

File: lib/sources/chain/chain_source_impl.dart [hunk 2]
```diff
@@ -159,7 +159,13 @@ class ChainSourceImpl extends ChainSource {
     }
 
     final data = TxData(messages: messages, wallet: wallet, feeAmount: fees);
-    return compute(sendTxBackground, data);
+
+    TransactionResult txResults = await compute(sendTxBackground, data);
+    // logs to sentry
+    if (!txResults.success) {
+      Logger.log(txResults.error);
+    }
```
Comment (rmontagnin) [inline lib/sources/chain/chain_source_impl.dart]: Just a small change to make it more readable from Sentry:

```suggestion
    if (!txResults.success) {
      Logger.log("Error while sending transaction to the chain: ${txResults.error.errorMessage}");
    }
```

**Review by rmontagnin — APPROVED** [review]
