### PR TITLE
Posts sync fixes

### LINKED ISSUE #81: Post status is not updated if app is closed prematurely
## Generic information
- OS name and version: Android 9
- Application build code: `4102`
- Network type (mobile/Wi-Fi): Both

## Bug description
When a post is created, the following series of actions is performed: 

1. The post is created locally. 
2. The post is sent to the chain. 
3. If the transaction is successful or it fails, a push notification is sent to the device. 
4. The post status is updated based on the notification result. 

Unluckily, if the application is closed in between 2 and 3, the post status never gets updated. 

This is even more disturbing since refreshing the posts list does not update the post status even if it has already been sent to the chain. 

## Steps to reproduce
1. Create a post. 
2. Wait for the sync to complete. 
3. Close the app
4. Wait 15 seconds, then open again the app. 

The post will be in the wrong state (its background is going to stay dimmed). 
Even refreshing the posts list, the status is not updated.

## Expected behavior
The post status should be updated and sent as being stored online if the remote contents are equals to the local ones.

### PR DESCRIPTION
**Pull request by rmontagnin**
## Description
- Fixed a bug that caused the posts to never update their status when synced to the chain (closes #81).
- Fixed a bug that caused the home list to throw an exception due to a bad setState call 

## Checklist
- [x] Targeted PR against correct branch.
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [x] Wrote unit tests.
- [x] Run flutter format.
- [ ] Updated the documentation.
- [ ] Added an entry to the `CHANGELOG.md` file.
- [ ] Re-reviewed `Files changed` in the Github PR explorer.

### CODE REVIEW

File: lib/ui/widgets/post_content/widgets/link_preview/index.dart [hunk 1]
```diff
@@ -22,9 +23,9 @@ class _LinkPreviewState extends State<LinkPreview> {
   void initState() {
     super.initState();
     fetchPreview(widget.urls).then((RichLinkPreview res) {
-      setState(() {
-        data = res;
-      });
+      if (mounted) {
+        setState(() => data = res);
+      }
```
Comment (ryuash) [inline lib/ui/widgets/post_content/widgets/link_preview/index.dart:28]: just curious where does mounted come from? :O

**Review by ryuash — APPROVED** [review]

File: lib/ui/widgets/post_content/widgets/link_preview/index.dart (hunk 1 above)
Comment (rmontagnin) [reply lib/ui/widgets/post_content/widgets/link_preview/index.dart:28]: @ryuash It's a property of the `State` class: [`mounted` property](https://api.flutter.dev/flutter/widgets/State/mounted.html) :grin:
